/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ly;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.annotation.WebServlet;

@WebServlet("/page")
public class App extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void service(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		resp.setContentType("text/html;charset=utf-8");
		
		//action='login'填Servlet别名
		resp.getWriter().write("<form action='login' method='get'>");
		resp.getWriter().write("用户名：<input type='text' name='uname' value=''/><br/>");
		resp.getWriter().write("密码：<input type='password' name='pwd' value=''/><br/>");
		resp.getWriter().write("<input type='submit' value='登陆'/><br/>");
		resp.getWriter().write("</form>");
		resp.getWriter().write("</body>");
		resp.getWriter().write("</html>");
	}
}

